version: '3'
services:
  jupyter:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: laughter
    volumes:
      - "./:/home/jovyan/work"
    environment:
      - BASE_DIR=/home/jovyan/work
    ports:
      - "8888:8888"
    command: jupyter notebook --ip 0.0.0.0 --no-browser
